import ArrivalImg1 from "../../assets/Homepage/Arrivals/img1.png";
import ArrivalImg2 from "../../assets/Homepage/Arrivals/img2.png";
import ArrivalImg3 from "../../assets/Homepage/Arrivals/img3.png";
import ArrivalImg4 from "../../assets/Homepage/Arrivals/img4.png";
import ArrivalImg5 from "../../assets/Homepage/Arrivals/img5.png";
import ArrivalImg6 from "../../assets/Homepage/Arrivals/img6.png";
import Stars from "../../assets/Homepage/Arrivals/stars.png";

export const arrivalsMenFashion = [
    {
        image: ArrivalImg1,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg2,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: `red`,
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg3,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg4,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg5,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg6,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
];

export const arrivalsWomenFashion = [
    {
        image: ArrivalImg3,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg4,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg1,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg2,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: `red`,
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg5,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg6,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
];

export const arrivalsWomenAccessories = [
    {
        image: ArrivalImg1,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg2,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: `red`,
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg3,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg4,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg5,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg6,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
];

export const arrivalsMenAccessories = [
    {
        image: ArrivalImg1,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg2,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: `red`,
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg3,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg4,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg5,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg6,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
];

export const arrivalsDiscount = [
    {
        image: ArrivalImg1,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg2,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: `red`,
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg3,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg4,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg5,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
    {
        image: ArrivalImg6,
        name: "Long Dress",
        star: Stars,
        review: "4.1k",
        price: 95.5,
        color: "red",
        statues: "Almost Sold Out",
    },
];
