import ArrivalImg1 from "../../assets/Fashion/image11.jpg";
import ArrivalImg2 from "../../assets/Fashion/image12.jpg";
import ArrivalImg3 from "../../assets/Fashion/image14.jpg";
import ArrivalImg4 from "../../assets/Fashion/image15.jpg";
import ArrivalImg5 from "../../assets/Fashion/image20.jpg";
import ArrivalImg6 from "../../assets/Fashion/image24.jpg";
import ArrivalImg7 from "../../assets/Fashion/image19.jpg";
import ArrivalImg8 from "../../assets/Fashion/image25.jpg";
import ArrivalImg9 from "../../assets/Fashion/image29.jpg";
import ArrivalImg10 from "../../assets/Fashion/image30.jpg";
import ArrivalImg11 from "../../assets/Fashion/image35.jpg";
import ArrivalImg12 from "../../assets/Fashion/image41.jpg";
import Stars from "../../assets/Homepage/Arrivals/stars.png";

export const arrivalFilter = [
    {
        image: ArrivalImg1,
        name: "Pink Dress",
        star: Stars,
        review: "4.1k",
        price: 8.0,
        color: "red",
        type: "female",
        statues: "Almost Sold Out",
        Brand: "Brook",
    },
    {
        image: ArrivalImg2,
        name: "Top and Shorts",
        star: Stars,
        review: "4.1k",
        price: 12.0,
        color: `red`,
        type: "female",
        statues: "Almost Sold Out",
        Brand: "Brook",
    },
    {
        image: ArrivalImg3,
        name: "Brown Summer Wear",
        star: Stars,
        review: "4.1k",
        price: 15.0,
        color: "red",
        type: "female",
        statues: "Almost Sold Out",
        Brand: "Brook",
    },
    {
        image: ArrivalImg4,
        name: "Black Joggers",
        star: Stars,
        review: "4.1k",
        price: 12.0,
        color: "red",
        type: "female",
        statues: "Almost Sold Out",
        Brand: "Brook",
    },
    {
        image: ArrivalImg5,
        name: "Gucci Up and Down",
        star: Stars,
        review: "4.1k",
        price: 15.0,
        color: "red",
        type: "female",
        statues: "Almost Sold Out",
        Brand: "Brook",
    },
    {
        image: ArrivalImg6,
        name: "Black Long-sleeve Shirt",
        star: Stars,
        review: "4.1k",
        price: 16.0,
        color: "red",
        type: "female",
        statues: "Almost Sold Out",
        Brand: "Brook",
    },
    {
        image: ArrivalImg7,
        name: "Yellow Hoody",
        star: Stars,
        review: "4.1k",
        price: 20.0,
        color: "yellow",
        type: "male",
        statues: "In stock",
        Brand: "Brook",
    },
    {
        image: ArrivalImg8,
        name: "All Black Dior",
        star: Stars,
        review: "4.1k",
        price: 125.0,
        color: "black",
        type: "male",
        statues: "In stock",
        Brand: "Dior",
    },
    {
        image: ArrivalImg9,
        name: "Jean Jacket",
        star: Stars,
        review: "4.1k",
        price: 13.0,
        color: "jean",
        type: "male",
        statues: "In stock",
        Brand: "Brook",
    },
    {
        image: ArrivalImg10,
        name: "Brook White Top",
        star: Stars,
        review: "4.1k",
        price: 16.0,
        color: "white",
        type: "male",
        statues: "In stock",
        Brand: "Brook",
    },
    {
        image: ArrivalImg11,
        name: "Brook White Sweater",
        star: Stars,
        review: "4.1k",
        price: 125.0,
        color: "white",
        type: "male",
        statues: "In stock",
        Brand: "Brook",
    },
    {
        image: ArrivalImg12,
        name: "Black Dotted Scarf",
        star: Stars,
        review: "4.1k",
        price: 51.0,
        color: "dotted black",
        type: "male",
        statues: "In stock",
        Brand: "Brook",
    },
];
